" Install plug (run init.sh to install vim-plug if these commands fail
call plug#begin('~/.vim/plugged')

" Install vim plugins via plug
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
" Plug 'altercation/vim-colors-solarized'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'edkolev/promptline.vim'
Plug 'fatih/vim-go'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/vim-github-dashboard'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'kchmck/vim-coffee-script'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'vimoutliner/vimoutliner'
Plug 'pangloss/vim-javascript'
" Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
" Plug 'wakatime/vim-wakatime'
Plug 'godlygeek/tabular'
Plug 'tomtom/tcomment_vim'
Plug 'rking/ag.vim'
Plug 'othree/vim-autocomplpop'
" Plug 'StanAngeloff/php.vim'
Plug 'shawncplus/phpcomplete.vim'
Plug 'tpope/vim-db'

" Color schemes
Plug 'nightsense/office'
Plug 'archSeer/colibri.vim'

" Games
" Plug 'johngrib/vim-game-code-break'

" Finish installation of Plug plugins
call plug#end()

" Install vundle for plugins that don't work with Plug.
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Install the plugins that don't work with Plug.
Plugin 'VundleVim/Vundle.vim'
Plugin 'dsawardekar/wordpress.vim'

" Finish installation of Vundle plugins
call vundle#end()

" Set look and feel
filetype plugin indent on
syntax on
set background=dark
set number
colorscheme office-dark
"colorscheme colibri
"let g:solarized_termcolors=256
let laststatus=2
let g:airline_powerline_fonts=1
set autochdir

" Save and load views automatically
autocmd BufWinLeave ?* mkview 1
autocmd BufWinEnter ?* silent loadview 1

" Hide tool/menu bars in GVim
set guioptions-=m  " Remove menu bar
set guioptions-=T  " Remove tool bar
set guioptions-=r  " Remove right-hand scroll bar
set guioptions-=L  " Remove left-hand scroll bar

" Configure backup/swap/undo directories
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//
set undodir=~/.vim/.undo//

" Text hygene
set nobomb
set list listchars=tab:→\ ,trail:·,extends:#,nbsp:·,
set encoding=utf-8
set nowrap

set noexpandtab " Make sure that every file uses real tabs, not spaces
set shiftround  " Round indent to multiple of 'shiftwidth'
set smartindent " Do smart indenting when starting a new line
set autoindent  " Copy indent from current line, over to the new line

" Set the tab width
let s:tabwidth=4
exec 'set tabstop='    .s:tabwidth
exec 'set shiftwidth=' .s:tabwidth
exec 'set softtabstop='.s:tabwidth
